#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Thu Oct 16 16:32:28 2008

import wx

# begin wxGlade: extracode
from CaLib import EpicsChannel
chStart=EpicsChannel("X02DA-ES1-ROBO:START")
chStop=EpicsChannel("X02DA-ES1-ROBO:STOP")
chStatus=EpicsChannel("X02DA-ES1-ROBO:FEEDBACK")



lastVal=-1

lastVal=-1

# end wxGlade



class StartGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: StartGUI.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_Start = wx.Button(self, -1, "Start")
        self.text_ctrl_Status = wx.TextCtrl(self, -1, "")
        self.button_Stop = wx.Button(self, -1, "Stop")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_start_press, self.button_Start)
        self.Bind(wx.EVT_TEXT, self.updateStatus, self.text_ctrl_Status)
        self.Bind(wx.EVT_BUTTON, self.button_stop_press, self.button_Stop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: StartGUI.__set_properties
        self.SetTitle("Start Screen")
        self.button_Start.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.button_Stop.SetBackgroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: StartGUI.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(8, 8, 0, 0)
        grid_sizer_1.Add(self.button_Start, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_Status, 0, 0, 0)
        grid_sizer_1.Add(self.button_Stop, 0, 0, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def button_start_press(self, event): # wxGlade: StartGUI.<event_handler>
        print "Event handler `button_start_press' not implemented!"
    	frame_2 = LoadingPanel(None, -1, "")
    	RoboGUI.SetTopWindow(frame_1)
    	frame_2.Show()
    	#RoboGUI.MainLoop()
        event.Skip()

    def updateStatus(self, event): # wxGlade: StartGUI.<event_handler>
        chStatus.putVal(self.text_ctrl_Status.GetValue())
        event.Skip()

    def button_stop_press(self, event): # wxGlade: StartGUI.<event_handler>
        print "Event handler `button_stop_press' not implemented!"
        event.Skip()

# end of class StartGUI


class LoadingPanel(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LoadingPanel.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.spin_button_sampleNumber = wx.SpinButton(self, -1 )
        self.text_ctrl_SampleName = wx.TextCtrl(self, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_SPIN, self.updateLoadPanel, self.spin_button_sampleNumber)
        self.Bind(wx.EVT_TEXT, self.pushPanel, self.text_ctrl_SampleName)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LoadingPanel.__set_properties
        self.SetTitle("Loading Panel")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LoadingPanel.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.spin_button_sampleNumber, 0, 0, 0)
        sizer_3.Add(self.text_ctrl_SampleName, 0, 0, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
	
	lastVal=self.spin_button_sampleNumber.GetValue()
        # end wxGlade

    def updateLoadPanel(self, event): # wxGlade: LoadingPanel.<event_handler>
        lastVal=self.spin_button_sampleNumber.GetValue()
	curChan=EpicsChannel("X02DA-SCAN-CAM1:FILPRE0"+str(lastVal))
	self.text_ctrl_SampleName.SetValue(curChan.getVal())
        event.Skip()

    def pushPanel(self, event): # wxGlade: LoadingPanel.<event_handler>
        print "Event handler `pushPanel' not implemented!"
	lastVal=self.spin_button_sampleNumber.GetValue()
	curChan=EpicsChannel("X02DA-SCAN-CAM1:FILPRE0"+str(lastVal))
	curChan.putVal(self.text_ctrl_SampleName.GetValue())
        event.Skip()

# end of class LoadingPanel


if __name__ == "__main__":
    RoboGUI = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = StartGUI(None, -1, "")
    RoboGUI.SetTopWindow(frame_1)
    frame_1.Show()
    RoboGUI.MainLoop()
